import { Listing } from './types';

// Curated property images from Unsplash (free to use)
const IMAGES = {
    studio: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    apartment: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
        'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    ],
    house: [
        'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
        'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
        'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    shared: [
        'https://images.unsplash.com/photo-1525438160292-a4a860951216?w=800&q=80',
        'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&q=80',
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    ],
};

export const SEED_LISTINGS: Listing[] = [
    {
        id: '1',
        title: 'Cosy Studio Near UNSW — Bills Included',
        address: '14 High St',
        suburb: 'Kensington',
        state: 'NSW',
        postcode: '2033',
        lat: -33.9173,
        lng: 151.2286,
        pricePerWeek: 390,
        propertyType: 'studio',
        bedrooms: 0,
        bathrooms: 1,
        furnished: true,
        petFriendly: false,
        billsIncluded: true,
        availableFrom: '2026-04-01',
        description: 'A well-presented studio apartment in the heart of Kensington, just a 5-minute walk to UNSW. The space features a modern kitchen, a queen-sized murphy bed, and fast NBN internet. Water and electricity are included in the rent. Perfect for a single student or graduate.',
        images: [IMAGES.studio[0], IMAGES.studio[1], IMAGES.studio[2]],
        contactName: 'Sarah Chen',
        contactPhone: '0412 345 678',
        contactEmail: 'sarah.chen@raywhite.com',
        agency: 'Ray White Kensington',
        aiScore: 8.7,
        aiSummary: 'Outstanding value for a Kensington studio — bills included makes the true cost very competitive, and the 5-min walk to UNSW is a huge plus. Fully furnished means zero setup costs for first-time renters.',
        aiFlags: [],
        aiPositives: ['Bills included saves ~$80/week', 'Fully furnished — move in ready', '5 min walk to UNSW campus', 'Modern fit-out'],
        nearbyUni: 'UNSW Sydney',
        uniDistance: 0.4,
    },
    {
        id: '2',
        title: 'Spacious 1BR Apartment — Inner West Location',
        address: '55 Parramatta Rd',
        suburb: 'Camperdown',
        state: 'NSW',
        postcode: '2050',
        lat: -33.8882,
        lng: 151.1784,
        pricePerWeek: 520,
        propertyType: 'apartment',
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        petFriendly: true,
        billsIncluded: false,
        availableFrom: '2026-03-15',
        description: 'Bright and airy one-bedroom apartment in sought-after Camperdown. Features include polished timber floors, a renovated bathroom, and a private balcony with leafy outlook. Pets welcome. Close to cafes, Royal Prince Alfred Hospital, and University of Sydney.',
        images: [IMAGES.apartment[0], IMAGES.apartment[1], IMAGES.apartment[2]],
        contactName: 'Marcus Webb',
        contactPhone: '0422 567 890',
        contactEmail: 'm.webb@lj-hooker.com.au',
        agency: 'LJ Hooker Newtown',
        aiScore: 7.4,
        aiSummary: 'A solid 1-bedroom in a prime inner-west location — pet-friendly is rare at this price point. Budget extra for bills (~$60-80/week). Great for someone who wants space and a homey feel close to USyd.',
        aiFlags: ['Bills not included — budget extra'],
        aiPositives: ['Pets welcome — rare finding', 'Balcony with leafy outlook', '12 min to University of Sydney', 'Close to cafes and transport'],
        nearbyUni: 'University of Sydney',
        uniDistance: 1.2,
    },
    {
        id: '3',
        title: 'Shared House — 1 Room Available, Great Housemates',
        address: '7 Glebe Point Rd',
        suburb: 'Glebe',
        state: 'NSW',
        postcode: '2037',
        lat: -33.8802,
        lng: 151.1858,
        pricePerWeek: 280,
        propertyType: 'shared',
        bedrooms: 1,
        bathrooms: 2,
        furnished: true,
        petFriendly: false,
        billsIncluded: true,
        availableFrom: '2026-03-20',
        description: 'One room available in a friendly 4-bedroom share house on the leafy end of Glebe Point Road. The house has two bathrooms, a large open-plan kitchen/living area, and a private backyard. Current housemates are all university students (USyd + UTS). WiFi and all utilities included.',
        images: [IMAGES.shared[0], IMAGES.shared[1], IMAGES.shared[2]],
        contactName: 'Tom Nguyen (Current Tenant)',
        contactPhone: '0433 789 012',
        contactEmail: 'glebe.share@gmail.com',
        agency: 'Private landlord',
        aiScore: 9.1,
        aiSummary: 'Exceptional value — $280/week all-inclusive in Glebe is genuinely rare. Being listed by a current tenant (not an agent) suggests a genuine, pleasant living situation. The walk to USyd/UTS is very manageable.',
        aiFlags: [],
        aiPositives: ['$280/week with ALL bills included', 'Real housemate community', '15 min walk to USyd', 'Private backyard'],
        nearbyUni: 'University of Sydney',
        uniDistance: 1.8,
    },
    {
        id: '4',
        title: 'Modern Studio — City Fringe, Transport Hub',
        address: '302/88 Broadway',
        suburb: 'Ultimo',
        state: 'NSW',
        postcode: '2007',
        lat: -33.8849,
        lng: 151.1975,
        pricePerWeek: 450,
        propertyType: 'studio',
        bedrooms: 0,
        bathrooms: 1,
        furnished: true,
        petFriendly: false,
        billsIncluded: false,
        availableFrom: '2026-04-07',
        description: 'Stylish furnished studio on the 3rd floor of a boutique building in Ultimo. Minutes from UTS, Broadway Shopping Centre, and Central Station. The apartment has a full kitchen, double bed, study desk, and gym access included.',
        images: [IMAGES.studio[1], IMAGES.studio[2], IMAGES.studio[0]],
        contactName: 'Lin Properties',
        contactPhone: '02 9123 4567',
        contactEmail: 'rentals@linproperty.com.au',
        agency: 'Lin Property Management',
        aiScore: 7.9,
        aiSummary: 'A smart city-fringe pick for UTS students. At $450/week furnished it\'s fair for Ultimo. No bills included, so expect $500-$530/week total cost. Gym access is a bonus. Central location means excellent transport options.',
        aiFlags: ['No bills included'],
        aiPositives: ['3 min to UTS campus', 'Gym access included', 'Furnished with study desk', 'Central Station nearby'],
        nearbyUni: 'UTS (University of Technology Sydney)',
        uniDistance: 0.3,
    },
    {
        id: '5',
        title: 'Charming 2BR Terrace — Share with a Friend',
        address: '41 King St',
        suburb: 'Newtown',
        state: 'NSW',
        postcode: '2042',
        lat: -33.8963,
        lng: 151.1800,
        pricePerWeek: 680,
        propertyType: 'house',
        bedrooms: 2,
        bathrooms: 1,
        furnished: false,
        petFriendly: true,
        billsIncluded: false,
        availableFrom: '2026-04-14',
        description: 'Heritage terrace home with two bedrooms, original floorboards, and a renovated kitchen. Newtown\'s culture and café strip is at your doorstep. Perfect for two students to share — works out to $340/person/week. Cat or small dog considered.',
        images: [IMAGES.house[0], IMAGES.house[1], IMAGES.house[2]],
        contactName: 'Penny Hartley',
        contactPhone: '0445 321 099',
        contactEmail: 'phartley@mcgrath.com.au',
        agency: 'McGrath Newtown',
        aiScore: 7.1,
        aiSummary: 'Great Newtown terrace — $340/person/week when shared is solid value given the suburb. Heritage charm and Newtown village lifestyle included. Budget for bills on top. Pets are a rare perk.',
        aiFlags: ['Bills not included', 'No furniture — setup costs required'],
        aiPositives: ['$340/person when shared', 'Iconic Newtown location', 'Heritage character', 'Pets welcome'],
        nearbyUni: 'University of Sydney',
        uniDistance: 2.4,
    },
    {
        id: '6',
        title: 'Brand New 1BR with Parking — Close to Macquarie',
        address: '12 Epping Rd',
        suburb: 'Macquarie Park',
        state: 'NSW',
        postcode: '2113',
        lat: -33.7748,
        lng: 151.1199,
        pricePerWeek: 480,
        propertyType: 'apartment',
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        petFriendly: false,
        billsIncluded: false,
        availableFrom: '2026-05-01',
        description: 'Brand new apartment in the quiet suburb of Macquarie Park. Features floor-to-ceiling windows, a gourmet kitchen, and one secure underground car space. Walking distance to Macquarie University, Macquarie Centre shopping, and the metro station.',
        images: [IMAGES.apartment[3], IMAGES.apartment[0], IMAGES.apartment[1]],
        contactName: 'Alex Dao',
        contactPhone: '0411 234 567',
        contactEmail: 'alex@propertyworks.com.au',
        agency: 'Property Works',
        aiScore: 6.8,
        aiSummary: 'A fresh, modern 1BR with the bonus of onsite parking — rare for students who drive. Macquarie Uni is walkable. At $480/week unfurnished, add $60-80 for bills. Great if you have a budget and want new fixtures.',
        aiFlags: ['No furniture included', 'Higher price point for area'],
        aiPositives: ['Brand new fixtures', 'Secure parking included', 'Walking distance to Macquarie Uni', 'Metro station nearby'],
        nearbyUni: 'Macquarie University',
        uniDistance: 0.8,
    },
    {
        id: '7',
        title: 'Budget Shared Room — Central Location',
        address: '8 Pitt St',
        suburb: 'Haymarket',
        state: 'NSW',
        postcode: '2000',
        lat: -33.8785,
        lng: 151.2046,
        pricePerWeek: 210,
        propertyType: 'shared',
        bedrooms: 1,
        bathrooms: 1,
        furnished: true,
        petFriendly: false,
        billsIncluded: true,
        availableFrom: '2026-03-10',
        description: 'Furnished room in a larger shared apartment in Haymarket, very close to Central Station and Chinatown. Room has its own lock. All living areas shared with 4 others. WiFi and all bills included. Inspections by appointment.',
        images: [IMAGES.shared[1], IMAGES.shared[0], IMAGES.shared[2]],
        contactName: 'Jenny Li',
        contactPhone: '0432 109 876',
        contactEmail: 'jenli.rentals@gmail.com',
        agency: 'Private',
        aiScore: 5.9,
        aiSummary: 'The cheapest CBD-adjacent option we\'re seeing right now. For $210/week all-in, it\'s functional but expect a busy, compact shared space. Ideal for budget-focused students who are rarely home. Location is unbeatable for transit.',
        aiFlags: ['Shared with 4 others — limited privacy', '"Inspections by appointment" — see it before committing'],
        aiPositives: ['Only $210/week all-inclusive', 'Central Station 2 min walk', 'All bills included', 'Furnished room'],
        nearbyUni: 'UTS (University of Technology Sydney)',
        uniDistance: 1.1,
    },
    {
        id: '8',
        title: 'Newly Renovated Studio — Manly Beach Lifestyle',
        address: '3/22 The Corso',
        suburb: 'Manly',
        state: 'NSW',
        postcode: '2095',
        lat: -33.7978,
        lng: 151.2870,
        pricePerWeek: 560,
        propertyType: 'studio',
        bedrooms: 0,
        bathrooms: 1,
        furnished: true,
        petFriendly: false,
        billsIncluded: false,
        availableFrom: '2026-04-01',
        description: 'Newly renovated ground floor studio steps from Manly Beach. Features a brand new kitchen, ensuite bathroom, and private courtyard. The studio has no through-traffic and feels very private. Furnished with quality fittings. Beach lifestyle at your doorstep.',
        images: [IMAGES.studio[2], IMAGES.studio[0], IMAGES.studio[1]],
        contactName: 'Coast Realty Manly',
        contactPhone: '02 9977 8765',
        contactEmail: 'rentals@coastrealty.com.au',
        agency: 'Coast Realty',
        aiScore: 6.5,
        aiSummary: 'Premium beachside lifestyle at a premium price. $560/week is steep for a studio, but Manly is one of Sydney\'s most desirable suburbs. Factor in bills. Great choice if beach access and lifestyle matter more than budget optimisation.',
        aiFlags: ['Bills not included', 'High price for studio size', 'Far from most universities'],
        aiPositives: ['Steps from Manly Beach', 'Private courtyard', 'Brand new renovation', 'Furnished'],
        nearbyUni: 'Macquarie University',
        uniDistance: 9.2,
    },
    {
        id: '9',
        title: '3-Bed Share House — Griffith Uni Students Welcome',
        address: '19 Southport Rd',
        suburb: 'Southport',
        state: 'QLD',
        postcode: '4215',
        lat: -27.9783,
        lng: 153.3977,
        pricePerWeek: 250,
        propertyType: 'shared',
        bedrooms: 1,
        bathrooms: 2,
        furnished: true,
        petFriendly: true,
        billsIncluded: true,
        availableFrom: '2026-03-25',
        description: '1 room available in a 3-bedroom share house in Southport. The house is clean, spacious, and has a large backyard. Current housemates are Griffith Uni students. Very close to Gold Coast light rail. All bills included in the weekly rent. Pet considered (cat or small dog).',
        images: [IMAGES.shared[2], IMAGES.shared[0], IMAGES.house[1]],
        contactName: 'Riley Thompson',
        contactPhone: '0455 678 901',
        contactEmail: 'southportshare2026@gmail.com',
        agency: 'Private',
        aiScore: 8.9,
        aiSummary: 'Exceptional value on the Gold Coast. $250/week with ALL bills included in a proper house with a backyard — extremely difficult to beat. Light rail access to Griffith Uni makes this a top-tier student option in QLD.',
        aiFlags: [],
        aiPositives: ['$250/week everything included', 'Large backyard', 'Pets welcome', 'Light rail to Griffith Uni'],
        nearbyUni: 'Griffith University Gold Coast',
        uniDistance: 2.1,
    },
    {
        id: '10',
        title: 'Modern 1BR — St Kilda Road Corridor',
        address: '5/100 Albert Rd',
        suburb: 'South Melbourne',
        state: 'VIC',
        postcode: '3205',
        lat: -37.8409,
        lng: 144.9706,
        pricePerWeek: 490,
        propertyType: 'apartment',
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        petFriendly: false,
        billsIncluded: false,
        availableFrom: '2026-04-10',
        description: 'Stylish 1-bedroom apartment on the St Kilda Road corridor. City views from bedroom, modern bathroom, open plan living, and secure intercom entry. Tram to Melbourne CBD and RMIT right at the front door. 12-month lease preferred.',
        images: [IMAGES.apartment[1], IMAGES.apartment[0], IMAGES.apartment[2]],
        contactName: 'James Park',
        contactPhone: '03 9867 5432',
        contactEmail: 'jpark@abercrombie.com.au',
        agency: 'Abercrombie & Kent Property',
        aiScore: 7.2,
        aiSummary: 'Well-located Melbourne apartment with tram at the door — very convenient for RMIT and Melbourne Uni students. At $490/week unfurnished, add budget for bills and furniture. The city views and tram access justify the mid-tier pricing.',
        aiFlags: ['12-month lease preferred — less flexibility', 'No furniture included'],
        aiPositives: ['Tram at the door to CBD', 'City views from bedroom', 'Close to RMIT and Melbourne Uni', 'Secure building'],
        nearbyUni: 'RMIT University',
        uniDistance: 2.8,
    },
    {
        id: '11',
        title: 'Affordable Studio — Brunswick Vibes',
        address: '9 Sydney Rd',
        suburb: 'Brunswick',
        state: 'VIC',
        postcode: '3056',
        lat: -37.7693,
        lng: 144.9622,
        pricePerWeek: 340,
        propertyType: 'studio',
        bedrooms: 0,
        bathrooms: 1,
        furnished: true,
        petFriendly: true,
        billsIncluded: false,
        availableFrom: '2026-03-28',
        description: 'Character studio apartment above a Melbourne institution on Sydney Rd. Exposed brick walls, timber floors, north-facing window. Very walkable neighbourhood. Pets welcome. Furnished with vintage pieces. A real gem for a creative student.',
        images: [IMAGES.studio[0], IMAGES.studio[2], IMAGES.studio[1]],
        contactName: 'Eva Moretti',
        contactPhone: '0421 543 210',
        contactEmail: 'eva.moretti@melburn.com.au',
        agency: 'Melburn Real Estate',
        aiScore: 8.2,
        aiSummary: 'A charming Brunswick studio at $340/week — great value for Melbourne\'s most exciting inner-north suburb. Pets allowed. Vintage furnishing adds character. Bills on top, but for the location and vibe, this is a genuine find.',
        aiFlags: ['Bills not included'],
        aiPositives: ['Exposed brick character', 'Pets welcome', 'Sydney Rd café culture at your door', '$340/week furnished'],
        nearbyUni: 'RMIT University',
        uniDistance: 4.5,
    },
    {
        id: '12',
        title: 'Clean 1BR Near QUT — Furnished & Move-In Ready',
        address: '24 Boundary St',
        suburb: 'South Brisbane',
        state: 'QLD',
        postcode: '4101',
        lat: -27.4789,
        lng: 153.0193,
        pricePerWeek: 420,
        propertyType: 'apartment',
        bedrooms: 1,
        bathrooms: 1,
        furnished: true,
        petFriendly: false,
        billsIncluded: false,
        availableFrom: '2026-04-01',
        description: 'Well-maintained furnished 1-bedroom apartment in trendy South Brisbane. Minutes from the cultural precinct, South Bank Parklands, and QUT Gardens Point campus. Air conditioning, study nook, and a small balcony. Easy ferry access to the city.',
        images: [IMAGES.apartment[2], IMAGES.apartment[3], IMAGES.apartment[1]],
        contactName: 'Brisbane Living',
        contactPhone: '07 3222 4455',
        contactEmail: 'rent@brisbaneliving.com.au',
        agency: 'Brisbane Living Rentals',
        aiScore: 7.8,
        aiSummary: 'Excellent QUT pick — furnished, close to South Bank\'s cultural hub, and the study nook is a thoughtful touch. $420/week furnished is competitive for Brisbane\'s inner south. Ferry access to city is a nice bonus.',
        aiFlags: ['Bills not included'],
        aiPositives: ['Fully furnished with study nook', 'Walking distance to QUT', 'South Bank lifestyle', 'Ferry & bus access'],
        nearbyUni: 'QUT (Gardens Point)',
        uniDistance: 0.9,
    },
];

export function filterListings(listings: Listing[], filters: {
    maxPrice?: number;
    propertyType?: string[];
    furnished?: boolean | null;
    petFriendly?: boolean | null;
    billsIncluded?: boolean | null;
    searchQuery?: string;
}): Listing[] {
    return listings.filter(l => {
        if (filters.maxPrice && l.pricePerWeek > filters.maxPrice) return false;
        if (filters.propertyType && filters.propertyType.length > 0) {
            if (!filters.propertyType.includes(l.propertyType)) return false;
        }
        if (filters.furnished !== null && filters.furnished !== undefined) {
            if (l.furnished !== filters.furnished) return false;
        }
        if (filters.petFriendly !== null && filters.petFriendly !== undefined) {
            if (l.petFriendly !== filters.petFriendly) return false;
        }
        if (filters.billsIncluded !== null && filters.billsIncluded !== undefined) {
            if (l.billsIncluded !== filters.billsIncluded) return false;
        }
        if (filters.searchQuery) {
            const q = filters.searchQuery.toLowerCase();
            const match = l.title.toLowerCase().includes(q)
                || l.suburb.toLowerCase().includes(q)
                || l.address.toLowerCase().includes(q)
                || l.state.toLowerCase().includes(q)
                || (l.nearbyUni?.toLowerCase().includes(q) ?? false);
            if (!match) return false;
        }
        return true;
    });
}
